[package]
name = "rustls-async-test"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.172"
chrono = "0.4.41"
rustls = "0.23.27"
webpki-roots = "1.0.0"

[dependencies.nix]
version = "0.30.1"
features = ["net", "poll", "event"]